apiVersion: v1
kind: Service
metadata:
  labels:
    app: microdegree-deploy
  name: microdegree-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8501
  selector:
    app: microdegree-deploy
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microdegree-deploy
  name: microdegree-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microdegree-deploy
  template:
    metadata:
      labels:
        app: microdegree-deploy
    spec:
      containers:
      - image: replace
        name: cutom-image
        ports:
        - containerPort: 8501
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: microdegree-secrets
              key: db-password
